spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/againhello
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
    driver-class-name: org.postgresql.Driver

app:
  props:
    social:
      kakao:
        client-id: ece32edbba77663269c9d158d5b5c19e
        client-secret: X2hfJvo90ByffwKDhbpdwl8m2E9zGk2M
        redirect-uri: http://localhost:8080/be/member/kakao/callback
        token-uri: https://kauth.kakao.com/oauth/token
        user-info-uri: https://kapi.kakao.com/v2/user/me
        user-info-name-attribute-key: id
        client-name: Kakao
