spring:

  config:
    import: optional:file:.env

  datasource:
    url: jdbc:postgresql://localhost:5432/againhello
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
    driver-class-name: org.postgresql.Driver

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.aix.againhello.sms
  configuration:
    map-underscore-to-camel-case: true

oauth2:
  kakao:
    client-id: ef86fd03e574909afcdf090c36f7c583
    client-secret: F3k1AJiS65yf8nS7aVptks41A1k0iwzU
    redirect-uri: http://localhost:3000/member/kakao
    token-uri: https://kauth.kakao.com/oauth/token
    user-info-uri: https://kapi.kakao.com/v2/user/me

jwt:
  secret: #!J)I#FD!IN#EJ#)JRINDIF!#*RJ#!)!#JED
  access-token-validity-in-seconds: 900    # 15분
  refresh-token-validity-in-seconds: 604800 # 7일


kakao:
  client-id: ef86fd03e574909afcdf090c36f7c583
  client-secret: F3k1AJiS65yf8nS7aVptks41A1k0iwzU
  redirect-uri: http://localhost:3000/member/kakao

aws:
  region: ${AWS_REGION:ap-northeast-2}
  credentials:
    access-key: ${AWS_ACCESS_KEY_ID:}
    secret-key: ${AWS_SECRET_ACCESS_KEY:}
  s3:
    bucket-name: ai-himedia