spring:
  config:
    import: optional:file:.env

  datasource:
    url: jdbc:postgresql://localhost:5432/againhello
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
    driver-class-name: org.postgresql.Driver

  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 315MB

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.aix.againhello.**
  configuration:
    map-underscore-to-camel-case: true

oauth2:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}
    redirect-uri: ${KAKAO_REDIRECT_URI}
    token-uri: https://kauth.kakao.com/oauth/token
    user-info-uri: https://kapi.kakao.com/v2/user/me

jwt:
  secret: ${JWT_SECRET}
  access-token-validity-in-seconds: 900
  refresh-token-validity-in-seconds: 604800

kakao:
  client-id: ${KAKAO_CLIENT_ID}
  client-secret: ${KAKAO_CLIENT_SECRET}
  redirect-uri: ${KAKAO_REDIRECT_URI}

aws:
  region: ap-northeast-2
  credentials:
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}
  s3:
    bucket-name: ai-himedia

clova:
  speech:
    secret: ${CLOVA_SPEECH_SECRET}
    invoke-url: ${CLOVA_SPEECH_INVOKE_URL}

file:
  upload:
    dir: upload
    max-count: 3
    allowed-audio-extensions: mp3,aac,ac3,ogg,flac,wav,m4a
    allowed-video-extensions: avi,mp4,mov,wmv,flv,mkv
    max-audio-size: 5242880
    max-video-size: 314572800
  output:
    dir: ./output