# .github/workflows/flutter-build.yml

name: Flutter Build

on:
  push:
    paths:
      - "flutter/**"
    branches: [dev]

jobs:
  build-flutter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.0"

      - name: Install & Build APK
        run: |
          cd mobile-flutter
          flutter pub get
          flutter build apk --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: flutter-apk
          path: flutter/build/app/outputs/flutter-apk/app-release.apk
