name: Python Docker Deploy

on:
  push:
    branches: [cjh]
    paths:
      - "python/**"
      - ".github/workflows/python.yml"
      - "Pipfile"
      - "Pipfile.lock"
      - "python/Dockerfile" # Dockerfile 경로를 명시적으로 감시

jobs:
  Python_Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Docker 로그인
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker 이미지 빌드
        run: docker build --build-arg PYTHON_VERSION=3.11 -t ${{ secrets.DOCKERHUB_USERNAME }}/python:${{ github.sha }} -f ./python/Dockerfile ./python

      - name: Docker 이미지 취약점 스캔
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/python:${{ github.sha }}
          format: table
          exit-code: 0
          severity: CRITICAL,HIGH

      - name: Docker 이미지 푸시
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/python:${{ github.sha }}

      - name: EC2에서 Docker 컨테이너 실행 (SSH 접속)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            # 기존 컨테이너가 있으면 중지 및 삭제
            docker stop python-app || true
            docker rm python-app || true
            # 최신 Docker 이미지 가져오기
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/python:${{ github.sha }}
            # Docker 컨테이너 실행 (환경 변수 전달)
            docker run -d --name python-app -p 8000:8000 \
              -e GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }} \
              -e LANGCHAIN_TRACING_V2=${{ secrets.LANGCHAIN_TRACING_V2 }} \
              -e LANGSMITH_TRACING_V2=${{ secrets.LANGSMITH_TRACING_V2 }} \
              -e LANGSMITH_ENDPOINT=${{ secrets.LANGSMITH_ENDPOINT }} \
              -e LANGSMITH_API_KEY=${{ secrets.LANGSMITH_API_KEY }} \
              -e LANGSMITH_PROJECT=${{ secrets.LANGSMITH_PROJECT }} \
              -e PERPLEXITY_KEY=${{ secrets.PERPLEXITY_KEY }} \
              -e CLAUDE_KEY=${{ secrets.CLAUDE_KEY }} \
              -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
              -e DB_HOST=${{ secrets.DB_HOST }} \
              -e DB_PORT=${{ secrets.DB_PORT }} \
              -e DB_NAME=${{ secrets.DB_NAME }} \
              -e DB_USER=${{ secrets.DB_USER }} \
              -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
              -e REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }} \
              -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
              -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
              -e ELEVENLABS_API_KEY=${{ secrets.ELEVENLABS_API_KEY }} \
              ${{ secrets.DOCKERHUB_USERNAME }}/python:${{ github.sha }}
