name: Python Docker Deploy

on:
  push:
    branches: [cjh]
    paths:
      - "python/**"
      - ".github/workflows/python.yml"
      - "Pipfile"
      - "Pipfile.lock"
      - "python/Dockerfile"

jobs:
  Python_Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Docker 공간 확보
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker system prune -f
            docker image prune -af

      - name: Docker 로그인
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker 이미지 빌드 및 푸시
        run: |
          echo "${{ secrets.PYTHON_ENV }}" > python/.env
          echo "GOOGLE_APPLICATION_CREDENTIALS (Base64): ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}"
          echo 'Decoded GOOGLE_APPLICATION_CREDENTIALS:'
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" | base64 -d
          docker build \
            --build-arg GOOGLE_APPLICATION_CREDENTIALS_CONTENT="${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" \
            --build-arg PYTHON_VERSION=3.11 \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/python:${{ github.sha }} \
            -f ./python/Dockerfile ./python
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/python:${{ github.sha }}

      - name: EC2에서 Docker 컨테이너 실행 (SSH 접속)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker stop python-app || true
            docker rm python-app || true

            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/python:${{ github.sha }}

            docker run -d --name python-app --gpus all --runtime=nvidia --ipc=host --privileged --net=host \
              -e GOOGLE_APPLICATION_CREDENTIALS="/app/gcp_credentials/hello-again-ai-project.json" \
              -e LANGCHAIN_TRACING_V2="${{ secrets.LANGCHAIN_TRACING_V2 }}" \
              -e LANGSMITH_TRACING_V2="${{ secrets.LANGSMITH_TRACING_V2 }}" \
              -e LANGSMITH_ENDPOINT="${{ secrets.LANGSMITH_ENDPOINT }}" \
              -e LANGSMITH_API_KEY="${{ secrets.LANGSMITH_API_KEY }}" \
              -e LANGSMITH_PROJECT="${{ secrets.LANGSMITH_PROJECT }}" \
              -e PERPLEXITY_KEY="${{ secrets.PERPLEXITY_KEY }}" \
              -e CLAUDE_KEY="${{ secrets.CLAUDE_KEY }}" \
              -e OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}" \
              -e DB_HOST="${{ secrets.DB_HOST }}" \
              -e DB_PORT="${{ secrets.DB_PORT }}" \
              -e DB_NAME="${{ secrets.DB_NAME }}" \
              -e DB_USER="${{ secrets.DB_USER }}" \
              -e DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
              -e REDIS_PASSWORD="${{ secrets.REDIS_PASSWORD }}" \
              -e AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}" \
              -e AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
              -e ELEVENLABS_API_KEY="${{ secrets.ELEVENLABS_API_KEY }}" \
              ${{ secrets.DOCKERHUB_USERNAME }}/python:${{ github.sha }}
