# .github/workflows/springboot.yml

name: Spring Boot Docker Deploy

on:
  push:
    paths:
      - "springboot/**"
      - ".github/workflows/springboot.yml"
    branches: [dev]

jobs:
  SpringBoot_Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3

      # Gradle Wrapper 권한 수정
      - name: Give Gradle Wrapper execute permission
        run: chmod +x ./springboot/gradlew # gradlew 파일에 실행 권한을 부여

      # Gradle 빌드
      - name: Gradle 빌드
        run: |
          ./springboot/gradlew build -x test  # 테스트를 제외한 빌드 (필요에 따라 변경 가능)

      - name: Docker Build & Push
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker 이미지 빌드 및 푸시
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/SpringBoot:${{ github.sha }} ./springboot  # 경로 수정
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/SpringBoot:${{ github.sha }}

      - name: EC2에서 Docker 컨테이너 실행 (SSH 접속)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            # 기존 컨테이너가 있으면 중지 및 삭제
            docker stop SpringBoot || true
            docker rm SpringBoot || true
            # 최신 Docker 이미지 가져오기
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/SpringBoot:${{ github.sha }}
            # Docker 컨테이너 실행 (80번 포트에서 Spring Boot 앱 서빙)
            docker run -d --name SpringBoot -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/SpringBoot:${{ github.sha }}
